# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: panoirou <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/21 14:44:51 by panoirou          #+#    #+#              #
#    Updated: 2016/11/25 14:15:35 by panoirou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
FLAGS = -Wall -Wextra -Werror
SRCS = ./ft_display_file.c

all:
	$(CC) -o ft_display_file $(FLAGS) $(SRCS)

clean:
	rm -rf ft_display_file.o;

fclean: clean
	rm -rf ft_display_file
